# Generated by Django 4.0 on 2021-12-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_shop', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
